# file: roles/php/tasks/main.yml
---

- name: Install remi from remote repo
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Install php
  yum: 
    name: php
    enablerepo: remi,remi-php74
    state: present

- name: Install php modules
  yum:
    name:
    - php-mbstring
    - php-devel
    - php-opcache
    - php-soap
    - php-pdo
    - php-mcrypt
    - php-pecl-xdebug
    - php-xml
    - php-mysql
    - php-gd
    enablerepo: remi,remi-php74
    state: present
  notify:
  - restart httpd
